version: '2'
services:
  web:
    build: .
    image: constantineche/webapp
    ports:
      - "3000:3000"
    links:
      - mongo:mongo
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
